// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/hydra_agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HydraAgent_Call_FullMethodName      = "/hydraagent.HydraAgent/Call"
	HydraAgent_Subscribe_FullMethodName = "/hydraagent.HydraAgent/Subscribe"
)

// HydraAgentClient is the client API for HydraAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HydraAgent mirrors the Go engine.EngineClient interface over gRPC by
// tunneling each method call as JSON. The `engine` field selects which local
// engine session (e.g. "race" or "hoard") the agent routes the call to. This
// keeps the wire contract a thin, drift-free mirror of EngineClient: the agent
// json.Marshals ltclient return types, the front json.Unmarshals into the very
// same Go types — no per-type proto messages to keep in sync.
type HydraAgentClient interface {
	// Call invokes one EngineClient method (see internal/engine/grpcclient for
	// the method-name registry and JSON param/result envelopes).
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallReply, error)
	// Subscribe streams the engine event bus as JSON-encoded ltclient.Event
	// frames (mirror of EngineClient.SetEventHandler + SubscribeEvents).
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventFrame], error)
}

type hydraAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewHydraAgentClient(cc grpc.ClientConnInterface) HydraAgentClient {
	return &hydraAgentClient{cc}
}

func (c *hydraAgentClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallReply)
	err := c.cc.Invoke(ctx, HydraAgent_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hydraAgentClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HydraAgent_ServiceDesc.Streams[0], HydraAgent_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, EventFrame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HydraAgent_SubscribeClient = grpc.ServerStreamingClient[EventFrame]

// HydraAgentServer is the server API for HydraAgent service.
// All implementations must embed UnimplementedHydraAgentServer
// for forward compatibility.
//
// HydraAgent mirrors the Go engine.EngineClient interface over gRPC by
// tunneling each method call as JSON. The `engine` field selects which local
// engine session (e.g. "race" or "hoard") the agent routes the call to. This
// keeps the wire contract a thin, drift-free mirror of EngineClient: the agent
// json.Marshals ltclient return types, the front json.Unmarshals into the very
// same Go types — no per-type proto messages to keep in sync.
type HydraAgentServer interface {
	// Call invokes one EngineClient method (see internal/engine/grpcclient for
	// the method-name registry and JSON param/result envelopes).
	Call(context.Context, *CallRequest) (*CallReply, error)
	// Subscribe streams the engine event bus as JSON-encoded ltclient.Event
	// frames (mirror of EngineClient.SetEventHandler + SubscribeEvents).
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[EventFrame]) error
	mustEmbedUnimplementedHydraAgentServer()
}

// UnimplementedHydraAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHydraAgentServer struct{}

func (UnimplementedHydraAgentServer) Call(context.Context, *CallRequest) (*CallReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedHydraAgentServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[EventFrame]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedHydraAgentServer) mustEmbedUnimplementedHydraAgentServer() {}
func (UnimplementedHydraAgentServer) testEmbeddedByValue()                    {}

// UnsafeHydraAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HydraAgentServer will
// result in compilation errors.
type UnsafeHydraAgentServer interface {
	mustEmbedUnimplementedHydraAgentServer()
}

func RegisterHydraAgentServer(s grpc.ServiceRegistrar, srv HydraAgentServer) {
	// If the following call panics, it indicates UnimplementedHydraAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HydraAgent_ServiceDesc, srv)
}

func _HydraAgent_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HydraAgentServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HydraAgent_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HydraAgentServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HydraAgent_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HydraAgentServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, EventFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HydraAgent_SubscribeServer = grpc.ServerStreamingServer[EventFrame]

// HydraAgent_ServiceDesc is the grpc.ServiceDesc for HydraAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HydraAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hydraagent.HydraAgent",
	HandlerType: (*HydraAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _HydraAgent_Call_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _HydraAgent_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/hydra_agent.proto",
}
